#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("SplunkXamarinClient.Resource", IsApplication=true)]

namespace SplunkXamarinClient
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ModernHttpClient.Resource.String.library_name = global::SplunkXamarinClient.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050006
			public const int cancelTransactionButton = 2131034118;
			
			// aapt resource value: 0x7f050002
			public const int flushButton = 2131034114;
			
			// aapt resource value: 0x7f05000b
			public const int handleExceptionArgumentButton = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int handleExceptionNullButton = 2131034124;
			
			// aapt resource value: 0x7f05000e
			public const int httpClientButton = 2131034126;
			
			// aapt resource value: 0x7f050001
			public const int linearLayout1 = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int linearLayout2 = 2131034115;
			
			// aapt resource value: 0x7f050007
			public const int linearLayout3 = 2131034119;
			
			// aapt resource value: 0x7f05000a
			public const int linearLayout4 = 2131034122;
			
			// aapt resource value: 0x7f05000d
			public const int linearLayout5 = 2131034125;
			
			// aapt resource value: 0x7f050008
			public const int logEventButton = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int logEventLogLevelButton = 2131034121;
			
			// aapt resource value: 0x7f05000f
			public const int modernHttpClientButton = 2131034127;
			
			// aapt resource value: 0x7f050000
			public const int myButton = 2131034112;
			
			// aapt resource value: 0x7f050004
			public const int startTransactionButton = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int stopTransactionButton = 2131034117;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040006
			public const int cancelTransactionButtonText = 2130968582;
			
			// aapt resource value: 0x7f040003
			public const int flushButtonText = 2130968579;
			
			// aapt resource value: 0x7f040009
			public const int handleExceptionArgumentButtonText = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int handleExceptionNullButtonText = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int httpClientButtonText = 2130968587;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			// aapt resource value: 0x7f040008
			public const int logEventButtonText = 2130968584;
			
			// aapt resource value: 0x7f040007
			public const int logEventLogLevelButtonText = 2130968583;
			
			// aapt resource value: 0x7f04000c
			public const int modernHttpClientButtonText = 2130968588;
			
			// aapt resource value: 0x7f040002
			public const int nullreference = 2130968578;
			
			// aapt resource value: 0x7f040004
			public const int startTransactionButtonText = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int stopTransactionButtonText = 2130968581;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
